//modal actions
export const OPEN_SHARE_MODAL = "OPEN_SHARE_MODAL";
export const CLOSE_SHARE_MODAL = "CLOSE_SHARE_MODAL";
export const OPEN_POST_MODAL = "OPEN_POST_MODAL";
export const CLOSE_POST_MODAL = "CLOSE_POST_MODAL";
export const OPEN_GROUP_MODAL = "OPEN_GROUP_MODAL";
export const CLOSE_GROUP_MODAL = "CLOSE_GROUP_MODAL";
//

//Auth actions
export const AUTH = "AUTH";
export const AUTH_ERROR = "AUTH_ERROR";
export const AXIOS_ERROR = "AXIOS_ERROR";
export const LOGOUT = "LOGOUT";
export const PROFILE = "PROFILE";

//POST actions
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const FETCH_ALL = "FETCH_ALL";
export const DELETE = "DELETE";
export const LOADING = "LOADING";
export const SET_SELECTED_POST = "UPDATE";
export const CLEAR_SELECTED_POST = "CLEAR_SELECTED_POST";
//

//Group actions
export const GROUP_LOADING = "GROUP_LOADING";
export const FETCH_GROUP = "FETCH_GROUP";
export const CREATE_GROUP = "CREATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const GROUP_ERROR = "GROUP_ERROR";
export const SELECTED_GROUP = "SELECTED_GROUP";
export const CLEAR_SELECTED_GROUP = "CLEAR_SELECTED_GROUP";
export const CURRENT_GROUP_DETAILS = "CURRENT_GROUP_DETAILS";
export const CURRENT_GROUP_LOADING = "CURRENT_GROUP_LOADING";

//Group Post
export const OPEN_GROUP_POST_MODAL = "OPEN_GROUP_POST_MODAL";
export const CLOSE_GROUP_POST_MODAL = "CLOSE_GROUP_POST_MODAL";
export const GET_GROUP_POSTS = "GET_GROUP_POSTS";
export const CREATE_GROUP_POST = "CREATE_GROUP_POST";
export const UPDATE_GROUP_POST = "UPDATE_GROUP_POST";
export const DELETE_GROUP_POST = "DELETE_GROUP_POST";
export const GROUP_POST_LOADING = "GROUP_POST_LOADING";

//snackbar actions
export const SUCCESS = "SUCCESS";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const ERROR = "ERROR";

//share actions
export const SHARE_POST = "SHARE_POST";
export const SHARE_POST_LOADING = "SHARE_POST_LOADING";
export const SHARE_POST_ERROR = "SHARE_POST_ERROR";
export const FETCH_SHARE_POST_LOADING = "FETCH_SHARE_POST_LOADING";
export const FETCH_SHARE_POST = "FETCH_SHARE_POST";
export const FETCH_EDITOR_ACCESS = "FETCH_EDITOR_ACCESS";
export const FETCH_VIEWER_ACCESS = "FETCH_VIEWER_ACCESS";
export const UPDATE_SHARED_POST = "UPDATE_SHARED_POST";
export const REMOVE_FROM_SHARED_POST = "REMOVE_FROM_SHARED_POST";
export const GET_ALL_FAVORITES = "GET_ALL_FAVORITES";
export const CLEAR_SELECTED_SHARED_POST = "CLEAR_SELECTED_SHARED";
export const SET_SELECTED_SHARED_POST = "SET_SELECTED_SHARED_POST";
